# Generated by Django 3.2.8 on 2021-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0002_auto_20211012_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_five',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image_two',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='Victoria Matosa (59).jpg', upload_to='static/images/orders/'),
            preserve_default=False,
        ),
    ]
