# Generated by Django 3.2.8 on 2021-10-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0004_remove_order_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='static/images/orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_main.order')),
            ],
        ),
    ]
